### ISSUE TITLE
Could not register successfully.

### ISSUE THREAD

**Issue by hash070** [exzork/GCAuth#11]
![image](https://user-images.githubusercontent.com/62081013/167903369-f6db344f-292c-4639-b519-f5d9143b3901.png)

Is that means I have to replace the grasscutter's default certificate with a legal domain certificate?

**Comment by hash070** [comment]
![image](https://user-images.githubusercontent.com/62081013/167903436-b6df3f13-f4a7-49b9-be78-c78de323abb7.png)

**Comment by exzork** [comment]
Yeah, you need to have valid ssl certificate. Also that website is using fetch and running in browser which doesn't support `unsecure ssl`. Try to use grassclipper instead and see if that's working.

**Comment by hash070** [comment]
> Yeah, you need to have valid ssl certificate. Also that website is using fetch and running in browser which doesn't support `unsecure ssl`. Try to use grassclipper instead and see if that's working.

OK,I got it.
Thanks for your reply.
