### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by izhuolin** [exzork/GCAuth#8]
Hello, I used the plug-in and ran successfully. So how can I register or change my password?

**Comment by exzork** [comment]
> Hello, I used the plug-in and ran successfully. So how can I register or change my password?

- for login/registering you can use Grassclipper and [GCTools](https://gc-tools.exzork.me)
- for changing password you can use [GCTools](https://gc-tools.exzork.me)
- or you can send request to endpoint described in readme if you wanna implement your own

**Comment by izhuolin** [comment]
Thank you for your answer
